# Generated by Django 3.2.9 on 2021-11-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fiber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('cleaning', models.TextField(default='', max_length=200)),
                ('saving', models.TextField(blank=True, default='', max_length=200)),
                ('feature', models.TextField(blank=True, default='', max_length=200)),
                ('caution', models.TextField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
