# Generated by Django 3.2.9 on 2021-11-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiber',
            old_name='save',
            new_name='saving',
        ),
        migrations.AlterField(
            model_name='fiber',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
