# Generated by Django 3.2.9 on 2021-11-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiber',
            name='image',
        ),
    ]
