# Generated by Django 3.2.9 on 2021-11-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_fiber_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiber',
            name='caution',
        ),
        migrations.RemoveField(
            model_name='fiber',
            name='cleaning',
        ),
        migrations.RemoveField(
            model_name='fiber',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='fiber',
            name='save',
        ),
    ]
