# Generated by Django 3.2.9 on 2021-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20211112_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiber',
            name='cleaning',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fiber',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
