# Generated by Django 3.2.9 on 2021-11-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20211112_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiber',
            name='save',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
