# Generated by Django 3.2.9 on 2021-11-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vueTest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='VueTest',
        ),
    ]
