# Generated by Django 3.2.9 on 2021-11-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryYoursApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='', verbose_name='내용'),
        ),
    ]
