# Generated by Django 3.2.9 on 2021-11-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaundryYoursApp', '0002_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
